schedule_calendar/urls.py
from django.urls import path, include
from . import views, email_handling

app_name = 'schedule_calendar'

urlpatterns = [
    path('', views.index),
    path('accounts/', include('django.contrib.auth.urls')),
    path('verifying/', views.verifying, name='verifying'),
    path('activate/<uidb64>/<token>', email_handling.activate, name='activate'),
    path('signup/', views.signup, name='signup'),
    path('profile/edit/', views.profile, name='profile'),
    path('logout/', views.index),

    path('check_if_user_exists/<check_user>', views.address_book, name='check_if_user'),
    path('address_book/<check_user>', views.address_book, name='address_book'),

    path('calendar/', views.CalendarView.as_view(), name='calendar'),

    path('event/new/', views.event, name='event_new'),
    path('calendar/event/edit/<event_id>/', views.event, name='event_edit'),
    path('event_delete/', views.event_delete, name='event_delete'),

    path('invite/', views.invite, name='invite'),
    path('invite_result/<uidb64>/<token>/<participant>/<result>', email_handling.invite_result, name='invite_result'),
    path('invite_response/', views.invite_response, name='invite_response'),
    path('remove_participant/', views.remove_participant, name='remove_participant'),
]

schedule_share/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schedule_calendar.urls')),
]

schedule_calendar/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
# from phonenumber_field.modelfields import PhoneNumberField


class Address(models.Model):
    street_address = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=75, blank=True)
    state = models.CharField(max_length=25, blank=True)
    zipcode = models.CharField(max_length=200, blank=True)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True)
    address = models.ForeignKey(Address, on_delete=models.CASCADE, blank=True, null=True)
    avatar_url = models.URLField(blank=True)
    contacts = models.ManyToManyField(User, blank=True, related_name='contacts')


class Event(models.Model):
    event_name = models.CharField(max_length=200)
    description = models.TextField()
    event_address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True, blank=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True)

    readonly_fields = 'owner'

    def __str__(self):
        return self.event_name

    @property
    def get_html_url(self):
        url = reverse('calendar:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.event_name} </a>'


class Participant(models.Model):
    class Status(models.TextChoices):
        INVITED = 'Invited'
        ACCEPTED = 'Accepted'
        DECLINED = 'Declined'
    participants = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, blank=True)
    status = models.CharField(max_length=8, choices=Status.choices, default=None)

schedule_calendar/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm, DateInput, forms, EmailField

from schedule_calendar.models import Event, Profile, Participant, Address  # , AddressBook


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')


class AddressForm(ModelForm):
    class Meta:
        model = Address
        fields = ('street_address', 'city', 'state', 'zipcode')


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar_url',)


class EventForm(ModelForm):
    class Meta:
        model = Event
        # datetime-local is a HTML5 input type, format to make date time show on fields
        widgets = {
            'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = ('event_name', 'description', 'start_time', 'end_time', 'owner')

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        # input_formats to parse HTML5 datetime-local input to datetime field
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)


class InviteParticipantForm(ModelForm):
    class Meta:
        model = Participant
        fields = ('participants', 'event')


class CheckIfUserExists(forms.Form):
    email = EmailField(required=True)


# class AddToAddressBook(ModelForm):
#
#     class Meta:
#         model = AddressBook
#         fields = '__all__'

schedule_calendar/views.py
import calendar
import os
from datetime import datetime, date, timedelta

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.db import transaction
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.safestring import mark_safe
from django.views import generic
from dotenv import load_dotenv

from schedule_share.settings import DEFAULT_FROM_EMAIL
from .email_handling import EmailHandler
from .forms import EventForm, UserForm, ProfileForm, InviteParticipantForm, AddressForm, CheckIfUserExists
from .models import Event, Address, Participant, Profile
from .utils import Calendar

load_dotenv()


class CalendarView(generic.ListView):
    model = Event
    template_name = 'calendar/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # use today's date for the calendar
        today_date = get_date(self.request.GET.get('month', None))
        # Instantiate our calendar class with today's year and date
        current_calendar = Calendar(self.request.user, today_date.year, today_date.month)

        context['prev_month'] = prev_month(today_date)
        context['next_month'] = next_month(today_date)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = current_calendar.formatmonth(with_year=True)
        context['calendar'] = mark_safe(html_cal)

        return context


def prev_month(d):
    first = d.replace(day=1)
    previous_month = first - timedelta(days=1)
    month = 'month=' + str(previous_month.year) + '-' + str(previous_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    the_next_month = last + timedelta(days=1)
    month = 'month=' + str(the_next_month.year) + '-' + str(the_next_month.month)
    return month


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()


@login_required(login_url='')
def event(request, event_id=None):
    attendees = []
    events = Event.objects.filter(owner_id=request.user.id).values()
    participants = Participant.objects.filter(event_id=event_id).filter(status='Accepted').values()
    attendees_ids = [participant['participants_id'] for participant in participants]
    for attendee_id in attendees_ids:
        attendees.append(User.objects.filter(pk=attendee_id).values()[0])
    print('Events: ', events, '\nParticipants: ', participants, '\nAttendees: ', attendees)

    participant_data = zip(participants, attendees)

    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
        if instance.owner.id == request.user.id:
            instance.owner = request.user
        if instance.event_address:
            address_instance = Address.objects.get(id=instance.event_address.id)
        else:
            address_instance = Address()
    else:
        instance = Event()
        instance.owner = request.user
        address_instance = Address()

    form = EventForm(request.POST or None, instance=instance)
    address_form = AddressForm(request.POST or None, instance=address_instance)

    if request.POST and form.is_valid():
        event = form.save(commit=False)
        address = address_form.save(commit=False)

        if event_id:
            if request.user.id == instance.owner.id:
                address.save()
                print('Address id in else: ', address.id)
                if address.id:
                    event.event_address_id = address.id

                event.owner = request.user
                event.save()
                return redirect('schedule_calendar:calendar')
            else:
                messages.error(request, 'You cannot edit this event!', 'danger')
        else:
            address.save()
            print('Address id in else: ', address.id)
            event.event_address_id = address.id
            event.owner = request.user
            event.save()

            return redirect('schedule_calendar:calendar')

    return render(request, 'calendar/event.html', {
        'form': form,
        'events': events,
        'address_form': address_form,
        'participant_data': participant_data,
    })


@login_required(login_url='')
def invite(request, participant_id=None):
    if participant_id:
        participant_instance = get_object_or_404(Participant, pk=participant_id)
    else:
        participant_instance = Participant()

    form = InviteParticipantForm(request.POST or None, instance=participant_instance)
    if request.POST and form.is_valid():
        """ For future use """
        # account_sid = os.environ['ACCOUNT']
        # token = os.environ['TOKEN']
        current_event = Event.objects.get(id=request.POST['event'])
        print('Username: ', request.POST['participants'])
        user = User.objects.get(id=request.POST['participants'])
        if current_event.owner_id == request.user.id:
            participant = form.save(commit=False)
            participant.event = current_event
            participant.participants = user
            participant.status = participant.Status.INVITED
            participant.save()
            print('Event: ', current_event, ' Participants: ', participant.participants)

        else:
            message = ['You do not own this event!']
            return render(request, 'calendar/invite_participant.html', {
                'form': form,
                'messages': message
            })

        invite_email = EmailHandler(
            current_user=request.user,
            template='calendar/invitation.html',
            from_email=request.user.email,
            recipient=user,
            to_email=user.email,
            subject='Event Invitation',
            current_site=get_current_site(request),
            current_event=current_event,
            participant=participant
        )
        sent = invite_email.send()

        print('Sent: ', sent)
        if sent == 1001:
            messages.error('An error has occurred, please try again!')

        return redirect('schedule_calendar:calendar')

    return render(request, 'calendar/invite_participant.html', {'form': form})


def invite_response(request):
    return render(request, 'calendar/invite_response.html')


@transaction.atomic
def signup(request):
    address_form = AddressForm(request.POST or None)
    user_form = UserForm(request.POST or None)
    profile_form = ProfileForm(request.POST or None)

    if request.method == 'POST':

        email = user_form['email'].value()
        if user_form.is_valid() and not get_user(email):

            address = address_form.save(commit=False)
            user = user_form.save(commit=False)
            user.is_active = False
            user.save()

            address.save()

            new_profile = profile_form.save(commit=False)
            new_profile.user_id = user.id
            new_profile.address_id = address.id
            new_profile.save()

            confirmation_email = EmailHandler(
                current_user=user,
                template='calendar/email.html',
                from_email=DEFAULT_FROM_EMAIL,
                recipient=user,
                to_email=user.email,
                subject='Email Verification',
                current_site=get_current_site(request)
            )
            sent = confirmation_email.send()

            if sent == 1001:
                messages.error('An error has occurred, please try again!')
                redirect('schedule_calendar:signup')

            return redirect('schedule_calendar:verifying')
        else:

            if not user_form.is_valid():
                message = 'Username already exists'
            elif email:
                message = 'User email already exists'

            user_form = UserForm()
            # =gJZxtbrTQ)C4]FM
            return render(request, "registration/signup.html", {
                'address_form': address_form,
                'user_form': user_form,
                'profile_form': profile_form,
                'messages': [message],
            })
    else:
        return render(request, "registration/signup.html", {
            'address_form': address_form,
            'user_form': user_form,
            'profile_form': profile_form,
        })


@login_required(login_url='')
def profile(request):
    profile_instance = Profile.objects.get(user_id=request.user.id)

    if profile_instance:
        address_instance = get_object_or_404(Address, pk=profile_instance.address_id)
    else:
        address_instance = Address()

    address_form = AddressForm(request.POST or None, instance=address_instance)
    profile_form = ProfileForm(request.POST or None, instance=profile_instance)

    if request.method == 'POST' and \
            address_form.is_valid() and \
            profile_form.is_valid():

        address = address_form.save()
        print('Address id: ', address.id)
        new_profile = profile_form.save(commit=False)
        new_profile.address_id = address.id
        new_profile.save()
        return redirect('schedule_calendar:calendar')
    else:
        return render(request, 'calendar/user_profile.html', {
            'address_form': address_form,
            'profile_form': profile_form,
        })


@login_required(login_url='')
def event_delete(request, event_id=None):
    print('Removing event...')


@login_required(login_url='')
def remove_participant(request):
    print('Removing participant...')


def verifying(request):
    return render(request, 'registration/verifying.html')


# @login_required(login_url='')
def get_user(email):

schedule_calendar/templates/calendar/add_participant.html
{% extends 'calendar/base.html' %}

{% block title %}
Add Participant
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'schedule_calendar:calendar' %}"> Calendar </a>
</div>

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
      {{ form }}
      {% for participant in participants %}
          <li>{{ participant | safe }}</li>
      {%  endfor %}
      <tr><td colspan="2"><button type="submit" name="add" class="btn btn-info right"> Add Participant </button></td></tr>
  </table>
</form>
{% endblock %}

schedule_calendar/templates/calendar/address_book.html
{% extends 'calendar/base.html' %}

{%  block title %}
    <h2>Address Book</h2>
{% endblock %}

{% block content %}
    <div class="clearfix">
      <a class="btn btn-info left" href="{% url 'schedule_calendar:calendar' %}"> Calendar </a>
    </div>
    {% include 'calendar/messages.html' %}
    <div class="container-fluid col-lg-12">
        <div class="row">
            <div class="container-fluid col-lg-6" id="left-side">
                <table class="table-responsive table-bordered">
                    <thead>
                        <tr>
                            <td>Avatar</td>
                            <td>Username</td>
                            <td>First Name</td>
                            <td>Last Name</td>
                            <td>Email</td>
                            <td>Street Address</td>
                            <td>City</td>
                            <td>State</td>
                            <td>Zipcode</td>
                        </tr>
                    </thead>
                    <tbody>
                        {% for contact, profile, address in contacts %}
                            <tr>
                                <td><img src="{{ profile.avatar_url }}"/></td>
                                <td>{{ contact.username }}</td>
                                <td>{{ contact.first_name }}</td>
                                <td>{{ contact.last_name }}</td>
                                <td>{{ contact.email }}</td>
                                <td>{{ address.street_address }}</td>
                                <td>{{ address.city }}</td>
                                <td>{{ address.state }}</td>
                                <td>{{ address.zipcode }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>

                </table>
            </div>
            <div class="container-fluid col-lg-6 id=right-side">
                <form action="{% url 'schedule_calendar:address_book' check_user=True %}" method="post">
                    {% csrf_token %}
                    <label for="email">Enter the email of the user you would like to add to your addressbook.</label><br>
                    {{ form }}
                    <button type="submit">Look Up User</button>
                </form>

                {% if user_exists %}
                    <form action="{% url 'schedule_calendar:address_book' check_user=False %}" method="post">
                        {% csrf_token %}
                        <label for="email">User exists would you like to add them to your addressbook?</label><br>
                        <button type="submit">Add User</button>
                    </form>
                {% elif user_not_exists %}
                    <form action="{% url 'schedule_calendar:address_book' check_user=True %}" method="post" >
                        {% csrf_token %}
                        <label for="email">Enter the email of the user you would like to add to your addressbook.</label><br>
                        {{ form }}
                        <button type="submit">Look Up User</button>
                    </form>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock %}

schedule_calendar/templates/calendar/base.html
<!doctype html>
{% load static %}

<html lang="en-US">

    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
      <link rel="stylesheet" type="text/css" href="{% static '/css/styles.css' %}">
      <title>Schedule Share Calendar App</title>
    </head>
    <body style="display: block; width: 100%">
        <header>
            <div class="navbar-fixed-top nav-top">
                <h1 class="title">Schedule Share</h1>
            </div>
        </header>

      {% block content %}
      {% endblock %}

      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

      {% block script %}
      {% endblock %}
    </body>
</html>

schedule_calendar/templates/calendar/calendar.html
{% extends 'calendar/base.html' %}
{% load static %}

{% block content %}
    <div class="dropdown" id="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                data-toggle="dropdown" aria-haspopup="false">
            <img src="{% static '/images/hamburger-btn-48px.svg' %}" alt="Hamburger Menu Icon" />
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenubutton">
            <a class="dropdown-item" href="{% url 'schedule_calendar:event_new' %}?{{ event }}">Add Event</a>
            <a class="dropdown-item" href="{% url 'schedule_calendar:event_delete' %}?{{ event }}">Remove Event</a>
            <a class="dropdown-item" href="{% url 'schedule_calendar:invite' %}">Participants</a>
            <a class="dropdown-item" href="{% url 'schedule_calendar:profile' %}?{{ profile }}">Update Profile</a>
            <a class="dropdown-item" href="{% url 'schedule_calendar:address_book' check_user=False %}">Address Book</a>
        </div>

    </div>
{% if user.is_authenticated %}
    <p>Hi {{ user.username }}!</p>
    <a href="{% url 'schedule_calendar:logout' %}">Log Out</a>
{% endif %}
    <div class="clearfix">
        <a class="btn btn-info left" href="{% url 'schedule_calendar:calendar' %}?{{ prev_month }}"> Previous Month </a>
    {#    <a class="btn btn-info center" href="{% url 'schedule_calendar:event_new' %}?{{ event }}"> Event </a>#}
        <a class="btn btn-info right" href="{% url 'schedule_calendar:calendar' %}?{{ next_month }}"> Next Month </a>
    </div>

    {{ calendar }}

    <div class="'clearfix">

    </div>
{% endblock %}

schedule_calendar/templates/calendar/email.html
{% autoescape off %}
Hi ,
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'schedule_calendar:activate' uidb64=uid token=token %}
{% endautoescape %}

schedule_calendar/templates/calendar/event.html
{% extends 'calendar/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'schedule_calendar:calendar' %}"> Calendar </a>
</div>
{% include 'calendar/messages.html' %}
    <div class="container-fluid col-lg-8" id="another-left-side">
        <table class="table-responsive table-bordered">
            <thead><td>Event Name</td><td>Start Date</td></thead>
            {% for event in events %}
                <tr>
                    <td>{{ event.event_name }}</td>
                    <td>{{ event.start_time }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="container-fluid col-lg-8" id="middle">
        <form method="post">
          {% csrf_token %}
          <table class="form form-table">
              {{ form }}
              {{ address_form }}
            <tr><td colspan="2"><button type="submit" name='submit' class="btn btn-info right"> Submit </button></td></tr>
          </table>
        </form>
    </div>
    <div class="container-fluid col-lg-8" id="another-right-side">
        <table class="table-responsive table-bordered">
            <thead><td>Participant Name</td><td>Status</td></thead>
            {% for participant, attendee in participant_data %}
                <tr>
                    <td>{{ attendee.first_name }} {{ attendee.last_name }}</td>
                    <td>{{ participant.status }}</td>
                </tr>
            {% endfor %}
        </table>
        <form method="post">
            {% csrf_token %}
            <tr><td colspan="2"><button type="submit" name='submit' class="btn btn-info right"> Submit </button></td></tr>
        </form>
    </div>


{% endblock %}

schedule_calendar/templates/calendar/event_owner_notification.html
{% extends 'calendar/base.html' %}
{% block title %}
    <h2>Invitation Response</h2>
{% endblock %}
{% block content %}
    Hi {{ user }},

    Your invitation to {{ sender }} for event {{ event_name }} has been {{ status }}.
    {% if status == 'Declined' %}
        Please login to select another participant if need be.
    {% endif %}
{% endblock %}

schedule_calendar/templates/calendar/invitation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Event Invitation</title>
</head>
<body>
    <p>Hi, {{ user }},

    I have an event I would like you to attend. Below are the details.

    Thanks,
    {{ sender }}</p>
    <table class="form form-table">
        <!-- TODO add in address fields and eventually maps accessibility  -->
        <tr><td colspan="2">Event:</td>td<td colspan="2">{{ event_name }}</td></tr>
        <tr><td colspan="2">Description:</td><td colspan="2">{{ description }}</td></tr>
        <tr><td colspan="2">Start Time:</td><td colspan="2">{{ start_time }}</td></tr>
        <tr><td colspan="2">End Time:</td><td colspan="2">{{ end_time }}</td></tr>
        <tr><td colspan="2">Address:</td></tr>
        <a href=""><tr><td colspan="2">{{ street_address }}</td></tr>
        <tr><td colspan="2">{{ city }}, {{ state }} {{ zipcode }}</td></tr></a>
        <tr>
            {% autoescape off %}
            <td colspan="2"><a href="http://{{ domain }}{% url 'schedule_calendar:invite_result' uidb64=uid token=token participant=participant_id result='accepted' %}">Accept</a></td>
            <td colspan="2"><a href="http://{{ domain }}{% url 'schedule_calendar:invite_result' uidb64=uid token=token participant=participant_id result='declined' %}">Decline</a></td>
            {% endautoescape %}
        </tr>
    </table>

</body>
</html>

schedule_calendar/templates/calendar/invite_participant.html
{% extends 'calendar/base.html' %}

{% block title %}
Add Participant
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'schedule_calendar:calendar' %}"> Calendar </a>
</div>
{% include 'calendar/messages.html' %}
<form method="post">
  {% csrf_token %}
  <table class="form form-table">
      {{ form }}
      {% for participant in participants %}
          <li>{{ participant | safe }}</li>
      {%  endfor %}
      <tr><td colspan="2"><button type="submit" name="add" class="btn btn-info right"> Invite Participant </button></td></tr>
  </table>
</form>
{% endblock %}

schedule_calendar/templates/calendar/invite_response.html
{% extends 'calendar/base.html' %}
{% block title %}
    <h2>Reponse Recorded</h2>
{% endblock %}
{% block content %}
    <p>Thank You, your response has been recorded!</p>
{% endblock %}

schedule_calendar/templates/calendar/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible alert-error">
      <button type="button" class="close" data-dismiss="alert">
      ×
      </button>
      <strong>{{message}}</strong>
    </div>
 {% endfor %}
{% endif %}

schedule_calendar/templates/calendar/user_profile.html
{% extends "calendar/base.html" %}

{% block title %}
Update Profile
{% endblock %}

{% block content %}
    <div class="clearfix">
      <a class="btn btn-info left" href="{% url 'schedule_calendar:calendar' %}"> Calendar </a>
    </div>
    <form method="post">
        {% csrf_token %}
         <table class="form form-table">
             {{ address_form }}
             {{ profile_form }}
             <tr><td colspan="2"><button type="submit">Update Profile</button></td></tr>
             <tr><td colspan="2"><a href='{% url 'schedule_calendar:login' %}'>Log In</a></td></tr>
         </table>
    </form>
{% endblock %}